version: "3.0"

services:
  #
  # The Oracle DB Definition
  #
  soadb:
    image: ${DC_REGISTRY_DB}/oracle/database:12.2.0.1-ee
    ports:
      - "${DC_ORCL_PORT}:1521"
      - "${DC_ORCL_OEM_PORT}:5500"
    environment:
      - ORACLE_SID=${DC_ORCL_SID}
      - ORACLE_PDB=${DC_ORCL_PDB}
      - ORACLE_PWD=${DC_ORCL_SYSPWD}
    container_name: soadb
    volumes:
      - ${DC_ORCL_DBDATA}:/opt/oracle/oradata

  #
  # The SOA Admin Server
  #
  soaas:
    image: ${DC_REGISTRY_SOA}/oracle/soasuite:${DC_SOA_VERSION}
    container_name: soaas
    command: /bin/bash -c "sleep 5s; /u01/oracle/dockertools/createDomainAndStart.sh"
    ports:
      - "7001:7001"
    environment:
      - DOMAIN_TYPE=soa
      - ADMIN_HOST=${DC_HOSTNAME}
      - ADMIN_PASSWORD=${DC_ADMIN_PWD}
      - CONNECTION_STRING=${DC_ORCL_HOST}:${DC_ORCL_PORT}/${DC_ORCL_PDB}
      - DB_PASSWORD=${DC_ORCL_SYSPWD}
      - DB_SCHEMA_PASSWORD=${DC_RCU_SCHPWD}
      - RCUPREFIX=${DC_RCU_SOAPFX}
      - MANAGED_SERVER=soa_server1
    volumes:
      - ${DC_DDIR_SOA}:/u01/oracle/user_projects

  #
  # The SOA Managed Server
  #
  soams:
    image: ${DC_REGISTRY_SOA}/oracle/soasuite:${DC_SOA_VERSION}
    container_name: soams
    depends_on:
      - "soaas"
    command: /bin/bash -c "/u01/oracle/dockertools/startMS.sh"
    ports:
      - "8001:8001"
      - "8002:8002"
    environment:
      - DOMAIN_TYPE=soa
      - ADMIN_HOST=${DC_HOSTNAME}
      - ADMIN_PORT=7001
      - adminhostname=${DC_HOSTNAME}
      - adminport=7001
      - MANAGED_SERVER=soa_server1
    volumes:
      - ${DC_DDIR_SOA}:/u01/oracle/user_projects

  #
  # The BPM Admin Server
  #
  bpmas:
    image: ${DC_REGISTRY_SOA}/oracle/soasuite:${DC_SOA_VERSION}
    container_name: bpmas
    command: /bin/bash -c "sleep 5s; /u01/oracle/dockertools/createDomainAndStart.sh"
    ports:
      - "7001:7001"
    environment:
      - DOMAIN_TYPE=bpm
      - ADMIN_HOST=${DC_HOSTNAME}
      - ADMIN_PASSWORD=${DC_ADMIN_PWD}
      - CONNECTION_STRING=${DC_ORCL_HOST}:${DC_ORCL_PORT}/${DC_ORCL_PDB}
      - DB_PASSWORD=${DC_ORCL_SYSPWD}
      - DB_SCHEMA_PASSWORD=${DC_RCU_SCHPWD}
      - RCUPREFIX=${DC_RCU_BPMPFX}
      - MANAGED_SERVER=soa_server1
    volumes:
      - ${DC_DDIR_BPM}:/u01/oracle/user_projects

  #
  # The BPM Managed Server
  #
  bpmms:
    image: ${DC_REGISTRY_SOA}/oracle/soasuite:${DC_SOA_VERSION}
    container_name: bpmms
    depends_on:
      - "bpmas"
    command: /bin/bash -c "/u01/oracle/dockertools/startMS.sh"
    ports:
      - "8001:8001"
      - "8002:8002"
    environment:
      - DOMAIN_TYPE=bpm
      - ADMIN_HOST=${DC_HOSTNAME}
      - ADMIN_PORT=7001
      - adminhostname=${DC_HOSTNAME}
      - adminport=7001
      - MANAGED_SERVER=soa_server1
    volumes:
      - ${DC_DDIR_BPM}:/u01/oracle/user_projects

  #
  # The OSB Admin Server
  #
  osbas:
    image: ${DC_REGISTRY_SOA}/oracle/soasuite:${DC_SOA_VERSION}
    container_name: osbas
    command: /bin/bash -c "sleep 5s; /u01/oracle/dockertools/createDomainAndStart.sh"
    ports:
      - "7001:7001"
    environment:
      - DOMAIN_TYPE=osb
      - ADMIN_HOST=${DC_HOSTNAME}
      - ADMIN_PASSWORD=${DC_ADMIN_PWD}
      - CONNECTION_STRING=${DC_ORCL_HOST}:${DC_ORCL_PORT}/${DC_ORCL_PDB}
      - DB_PASSWORD=${DC_ORCL_SYSPWD}
      - DB_SCHEMA_PASSWORD=${DC_RCU_SCHPWD}
      - RCUPREFIX=${DC_RCU_OSBPFX}
      - MANAGED_SERVER=osb_server1
    volumes:
      - ${DC_DDIR_OSB}:/u01/oracle/user_projects

  #
  # The OSB Managed Server
  #
  osbms:
    image: ${DC_REGISTRY_SOA}/oracle/soasuite:${DC_SOA_VERSION}
    container_name: osbms
    depends_on:
      - "osbas"
    command: /bin/bash -c "/u01/oracle/dockertools/startMS.sh"
    ports:
      - "9001:9001"
      - "9002:9002"
    environment:
      - DOMAIN_TYPE=osb
      - ADMIN_HOST=${DC_HOSTNAME}
      - ADMIN_PORT=7001
      - adminhostname=${DC_HOSTNAME}
      - adminport=7001
      - MANAGED_SERVER=osb_server1
    volumes:
      - ${DC_DDIR_OSB}:/u01/oracle/user_projects
